github runner being stupid, not keeping creds
Run docker login ***/*** -u *** -p ***
WARNING! Using -*** the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
The push refers to repository [***/***/dispute-api]
31840c2dc8bf: Preparing
6a810fee00bb: Preparing
6293dfcf2f90: Preparing
6e96e6a20e40: Preparing
88f62d0c715d: Preparing
bb50d1ecf116: Preparing
9eb82f04c782: Preparing
bb50d1ecf116: Waiting
9eb82f04c782: Waiting
unauthorized: authentication required
Error: Process completed with exit code 1.